# Generated by Django 5.0.2 on 2024-02-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdetails',
            fields=[
                ('Studentname', models.CharField(max_length=20)),
                ('Regno', models.IntegerField()),
                ('BookName', models.CharField(max_length=50)),
                ('AuthorName', models.CharField(max_length=50)),
                ('BookNo', models.IntegerField(primary_key=True, serialize=False)),
                ('YearofRelease', models.DateField()),
            ],
        ),
    ]
